vellm:
  build: .
  dockerfile: Dockerfile
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - AWS_DEFAULT_REGION
    - PORT
    - ENV
  ports:
    - "8080:8080"
